Add Home Kit Paper Instruction Page
Sage-Bionetworks/covidrecoverycorps pull request #736
Opened 2021-01-15 00:14 UTC by leonli33

Created a new page with path "/testkit" that displays a video to the user about home kit paper instructions.

The page looks as follows:
![image](https://user-images.githubusercontent.com/31671708/104664117-50215b80-5683-11eb-8d03-42c31af80d98.png)

Resolves #732

2021-01-15 17:18 UTC, conundrumgirl requested changes

2021-01-15 17:18 UTC, conundrumgirl commented on src/components/static/TestKitInformationScreen.tsx
> +import React, { useState } from 'react'
One general note is that this is responsive site so it should look OK no mobile. Please ping  me if you have implementation questions about it

2021-01-15 17:18 UTC, conundrumgirl commented on src/components/static/TestKitInformationScreen.tsx
> +          className={engishTextClasses.join(' ')}
In general for conditional classes it's easier to use template strings `${}` rather then manipulating an array and joining it

2021-01-15 17:18 UTC, conundrumgirl commented on src/components/static/TestKitInformationScreen.tsx
> +      <Iframe
do you need react-iframe? can you just use regular iframe? Another approach to this is just rendering different iframes depending on englishIsSelected.

2021-01-15 17:18 UTC, conundrumgirl commented on src/components/static/TestKitInformationScreen.tsx
> +        <div
It is preferable for an element that is used as a button to be an actual button rather then the div styled to look as one

2021-01-15 17:18 UTC, conundrumgirl commented on src/components/static/TestKitInformationScreen.tsx
> +
how about something like this const class = `${classes.languageText} ${classes.selectedLanguage}`

2021-01-18 00:23 UTC, conundrumgirl requested changes
Looks good. Just one change needed for how to handle the text.

2021-01-18 00:23 UTC, conundrumgirl commented on src/components/static/TestKitInformationScreen.tsx
> +        language === 'en'
the text should be in the translation files  (locales/../translation) and then you would use useTranslate hook. It checks the current language for you and selects the appropriate location. You can find usage example here: https://github.com/Sage-Bionetworks/covidrecoverycorps/blob/master/src/components/learningHub/LearningHub.tsx#L233

2021-01-18 03:50 UTC, leonli33 commented on src/components/static/TestKitInformationScreen.tsx
> +        language === 'en'
Got it!

2021-01-18 17:03 UTC, conundrumgirl approved these changes
Looks good!

2021-01-18 17:03 UTC, merged